---
- name: Ubuntu Server Update for Alamo Tech
  hosts: localhost
  gather_facts: false
  vars:
    client: "alamo-tech"
    client_dir: "clients/{{ client }}"
    deployment_type: "ubuntu-update"
    
  tasks:
    - name: List directory contents to debug
      shell: ls -la /tmp/semaphore/project_5/repository_3_template_3/
      register: dir_list
      
    - name: Debug directory contents
      debug:
        var: dir_list.stdout_lines
        
    - name: Check if targets.env exists
      shell: find /tmp/semaphore/project_5/repository_3_template_3/ -name "targets.env" -type f
      register: targets_file
      
    - name: Debug targets.env location
      debug:
        var: targets_file.stdout_lines
        
    - name: Load client configuration
      include_vars: "{{ targets_file.stdout_lines[0] }}"
      when: targets_file.stdout_lines | length > 0
      
    - name: Display deployment information
      debug:
        msg:
          - "Client: {{ client }}"
          - "Target Host: {{ HOST }}"
          - "SSH User: {{ USER }}"
          - "Deployment Type: {{ deployment_type }}"
          
    - name: Run Ubuntu update deployment
      shell: |
        cd /tmp/semaphore/project_5/repository_3_template_3
        ./shared/scripts/ubuntu_update.sh \
          --client "{{ client }}" \
          --client-dir "{{ client_dir }}" \
          --ssh-key "$SEMAPHORE_SECRET_DIR/ssh_key" \
          --host "{{ HOST }}" \
          --user "{{ USER }}" \
          --update-type "{{ UBUNTU_UPDATE_TYPE | default('standard') }}"
      register: update_result
      
    - name: Display update results
      debug:
        var: update_result.stdout_lines
        
    - name: Check for update errors
      fail:
        msg: "Ubuntu update failed"
      when: update_result.rc != 0
      
    - name: Update completed successfully
      debug:
        msg: "Ubuntu update completed successfully for {{ client }}"
