---
- name: Ubuntu Server Update for Alamo Tech
  hosts: localhost
  gather_facts: false
  vars:
    client: "alamo-tech"
    client_dir: "clients/{{ client }}"
    deployment_type: "ubuntu-update"
    # Alamo Tech configuration (hardcoded from targets.env)
    HOST: "100.106.25.78"
    USER: "ubuntu"
    ENVIRONMENT: "production"
    PROJECT: "alamo-tech"
    REGION: "us-central-1"
    UBUNTU_UPDATE_TYPE: "standard"
    AUTO_REBOOT: "false"
    DRY_RUN: "false"
    COMPANY_NAME: "Alamo Tech"
    DEPLOYMENT_TIER: "enterprise"
    MONITORING_ENABLED: "true"
    BACKUP_ENABLED: "true"
    
  tasks:
      
    - name: Display deployment information
      debug:
        msg:
          - "Client: {{ client }}"
          - "Target Host: {{ HOST }}"
          - "SSH User: {{ USER }}"
          - "Deployment Type: {{ deployment_type }}"
          
    - name: Check if script exists
      shell: ls -la /tmp/semaphore/project_5/repository_3_template_3/shared/scripts/ubuntu_update.sh
      register: script_check
      
    - name: Debug script check
      debug:
        var: script_check.stdout_lines
        
    - name: Check script permissions
      shell: ls -la /tmp/semaphore/project_5/repository_3_template_3/shared/scripts/
      register: script_perms
      
    - name: Debug script permissions
      debug:
        var: script_perms.stdout_lines
        
    - name: Run Ubuntu update deployment
      shell: |
        cd /tmp/semaphore/project_5/repository_3_template_3
        chmod +x ./shared/scripts/ubuntu_update.sh
        ./shared/scripts/ubuntu_update.sh \
          --client "{{ client }}" \
          --client-dir "{{ client_dir }}" \
          --ssh-key "$SEMAPHORE_SECRET_DIR/ssh_key" \
          --host "{{ HOST }}" \
          --user "{{ USER }}" \
          --update-type "{{ UBUNTU_UPDATE_TYPE | default('standard') }}"
      register: update_result
      
    - name: Display update results
      debug:
        var: update_result.stdout_lines
        
    - name: Check for update errors
      fail:
        msg: "Ubuntu update failed"
      when: update_result.rc != 0
      
    - name: Update completed successfully
      debug:
        msg: "Ubuntu update completed successfully for {{ client }}"
