# playbooks/site.yml
- hosts: localhost
  gather_facts: false
  vars:
    azure_client_id: "{{ lookup('env', 'AZURE_CLIENT_ID') }}"
    azure_tenant_id: "{{ lookup('env', 'AZURE_TENANT_ID') }}"
    azure_subscription_id: "{{ lookup('env', 'AZURE_SUBSCRIPTION_ID') }}"
    azure_client_secret: "{{ lookup('env', 'AZURE_CLIENT_SECRET') }}"
  pre_tasks:
    - name: Ensure Azure env vars are present
      assert:
        that:
          - azure_client_id | length > 0
          - azure_tenant_id | length > 0
          - azure_subscription_id | length > 0
          - azure_client_secret | length > 0
        fail_msg: "Missing one or more Azure env vars. Check the Semaphore Variable Group."
